name: abetal

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'apps/abetal/**'
      - 'libs/kafka/**'
      - '.github/workflows/abetal.yml'
      - 'build.gradle.kts'
      - 'Dockerfile.streams'
      - 'models/**'
  workflow_run:
      workflows: [pr]
      types: [completed]
      branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    steps:
      - run: echo "workflow gate validated"

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: check
    permissions:
      contents: write  # submit dependency-graph
      id-token: write  # publish docker image
      actions: read    #
      checks: write    # write test results
    steps:
      - uses: actions/checkout@v6
        with:
          # use sha from the merged pr or default to the current sha.
          ref: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_sha || github.sha }}
      - uses: actions/setup-java@v5.1.0
        with:
          java-version: 21
          distribution: temurin

      - uses: gradle/actions/setup-gradle@v5
        with:
          dependency-graph: generate-and-submit

      - run: ./gradlew apps:${{ github.workflow }}:test apps:${{ github.workflow }}:buildFatJar --continue --no-daemon

      - uses: dorny/test-reporter@v2.3.0
        if: success() || failure()
        with:
          name: tests
          path: "**/**/build/test-results/test/TEST-*.xml"
          reporter: java-junit
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: nais/docker-build-push@v0
        with:
          team: helved
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          image_suffix: ${{ github.workflow }}
          tag: ${{ github.sha }}
          dockerfile: ./apps/abetal/Dockerfile

  deploy-dev:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build
    permissions:
      contents: read    # read repository files
      id-token: write   # publish nais manifest
    steps:
      - uses: actions/checkout@v6
      - uses: nais/login@v0
        id: login
        with:
          team: helved
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
      - uses: nais/deploy/actions/deploy@v2
        env:
          PRINT_PAYLOAD: true
          CLUSTER: dev-gcp
          RESOURCE: apps/${{ github.workflow }}/dev.yml,apps/${{ github.workflow }}/alert.yml
          VAR: image=${{ steps.login.outputs.registry }}/${{ github.event.repository.name }}-${{ github.workflow }}:${{ github.sha }}

  # deploy-prod:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10
  #   needs: build
  #   permissions:
  #     contents: read    # read repository files
  #     id-token: write   # publish nais manifest
  #   steps:
  #     - uses: actions/checkout@v6
  #     - uses: nais/login@v0
  #       id: login
  #       with:
  #         team: helved
  #         identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
  #         project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
  #     - uses: nais/deploy/actions/deploy@v2
  #       env:
  #         PRINT_PAYLOAD: true
  #         CLUSTER: prod-gcp
  #         RESOURCE: apps/${{ github.workflow }}/prod.yml,apps/${{ github.workflow }}/alert.yml
  #         VAR: image=${{ steps.login.outputs.registry }}/${{ github.event.repository.name }}-${{ github.workflow }}:${{ github.sha }}
